MCU = atmega8535
#MCU = atxmega128a1
F_CPU = 16000000
TARGET = bluetooth_test
BASE = ..
ALMONDLIBS = bluetooth
SRC = bluetooth_test
EXTRAINCDIRS =
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../make/base.makefile 
