#MCU = atmega8535
MCU = atxmega128a1
F_CPU = 2000000
TARGET = bluetooth_test
BASE = ..
ALMONDLIBS = uart bluetooth
SRC = ../shared/error.c
EXTRAINCDIRS =
TARGETTYPE = SQUIRREL
include ../make/base.makefile 
