MCU = atmega8535
F_CPU = 16000000
TARGET = bluetooth_test
BASE = ..
ALMONDLIBS = downlink uplink
SRC = ../shared/error.c
EXTRAINCDIRS = ../drivers/ ../shared/
TARGETTYPE = SQUIRREL
include ../make/base.makefile 

