MCU = atxmega128a1
F_CPU = 2000000
TARGET = bluetooth
SRC = $(TARGET).c
BASE = ../../..
ALMONDLIBS = gui display bluetooth
TARGETTYPE = SQUIRREL
EXTRAINCDIRS = $(BASE)/squirrel/
ENABLE_DEBUG = 0
include $(BASE)/make/base.makefile


