MCU = atxmega128a1
F_CPU = 32000000
TARGET = display_test.c
SRC =  display_test.c
BASE = ../../..
ALMONDLIBS = display error button
EXTRAINCDIRS = $(BASE)/squirrel/
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../../../make/base.makefile 
