MCU = atxmega128a1
F_CPU = 32000000
TARGET = main
SRC = ../../../drivers/display/display.c ../../../drivers/display/display_draw.c ./main.c
EXTRAINCDIRS = ../
BASE = ../../..
ALMONDLIBS = display
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 0
include ../../../make/base.makefile


