MCU = atxmega128a1
F_CPU = 32000000
TARGET = menu_test.c
SRC =  menu_test.c
BASE = ../../..
ALMONDLIBS = display error button
EXTRAINCDIRS = ../../../drivers/ ../../../protocols/ ../../../shared/
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../../../make/base.makefile 
