MCU = atxmega128a1
F_CPU = 32000000
TARGET = squirrel
SRC =
BASE = ..
ALMONDLIBS = downlink uplink
EXTRAINCDIRS = ../drivers/ ../protocols/ ../shared/
TARGETTYPE = SQUIRREL
include ../make/base.makefile 

