MCU = atxmega128a1
F_CPU = 32000000
TARGET = squirrel
SRC =  ../drivers/display/display.c ../drivers/display/display_draw.c squirrel.c util.c 
BASE = ..
ALMONDLIBS = display downlink uplink storage rtc
EXTRAINCDIRS = ../drivers/ ../protocols/ ../shared/
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../make/base.makefile 

