MCU = atxmega128a1
F_CPU = 2000000
TARGET = main
SRC = $(TARGET).c # $(BASE)/drivers/twi/twi_master_driver.c
BASE = ../..
#ALMONDLIBS = error draw_toolkit rtc
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include $(BASE)/make/base.makefile


