MCU = atxmega128a1
F_CPU = 32000000
TARGET = fat16_test.c
SRC =  fat16_test.c
BASE = ../..
ALMONDLIBS = display sd error button
EXTRAINCDIRS = ../../drivers/ ../../protocols/ ../../shared/
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../../make/base.makefile 
