MCU = atxmega128a1
# Keep in sync with squirrel Makefile
#F_CPU = 27648000
F_CPU = 32000000
TARGET = fat16_test
SRC = fat16_test.c
BASE = ../..
ALMONDLIBS = draw_toolkit fat16 error
EXTRAINCDIRS = 
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../../make/base.makefile 
