MCU = atxmega128a1
F_CPU = 32000000
TARGET = sd_test.c
SRC =  sd_test.c
BASE = ../../..
ALMONDLIBS = display error button spi
EXTRAINCDIRS = ../../../drivers/ ../../../protocols/ ../../../shared/
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../../../make/base.makefile 
