MCU = atxmega128a1
F_CPU = 2000000
TARGET = display_test.c
SRC =  ../../drivers/display/display.c ../../drivers/display/display_draw.c display_test.c
BASE = ../..
ALMONDLIBS = display
EXTRAINCDIRS = ../../drivers/ ../../protocols/ ../../shared/
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 0
include ../../make/base.makefile 

