MCU = atxmega128a1
# Keep in sync with squirrel Makefile
F_CPU = 27648000
TARGET = spi_sd_test
SRC = spi_sd_test.c
BASE = ../..
ALMONDLIBS = draw_toolkit sd error
EXTRAINCDIRS =
TARGETTYPE = SQUIRREL
ENABLE_DEBUG = 1
include ../../make/base.makefile 
